## Créer un array NumPy

In [2]:
import numpy as np

revenus = [1800, 1500, 2200, 3000, 2172]

revenu_array = np.array(revenus)

revenu_array

array([1800, 1500, 2200, 3000, 2172])

## Quelques fonctions de base

### Array avec les zeros

In [6]:
array_zero = np.zeros([5,2])
print(array_zero)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


### Array des uns

In [7]:
array_un = np.ones([3,4])
array_un

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])